# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # systemd initrd 比传统 bash initrd 更现代、更快：
  # - 自动组装 MD/LVM/LUKS（systemd 原生驱动）
  # - systemd-hibernate-resume-generator 可自动探测 swapfile 偏移
  #   省掉 resume_offset 的手动维护（当前仍需显式写偏移做兜底）
  # - 如果用 Plymouth，图形化 LUKS 密码输入需要 systemd initrd
  boot.initrd.systemd.enable = true;

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXROOT";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/NIXBOOT";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # --- Zram 交换（内存压缩 swap）---
  # 日常桌面使用时优先走 zram（内存内压缩，比磁盘 swap 快）；
  # hibernate 时内核只写入真实 swapfile，不碰 zram。
  # 注意：zram 不能存休眠镜像，下方 /var/lib/swapfile 必须保留。
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
  };

  # --- Hibernate 配置（挂起到磁盘）---
  # 三要素：
  #   1) swap >= RAM（本机 RAM 27G，扩到 36G 留压缩镜像 + 余量）
  #   2) boot.resumeDevice —— 设了它，NixOS 自动生成 resume= 内核参数
  #   3) systemd-hibernate-resume（systemd >= 254 支持 FIEMAP 自动探测
  #      swapfile 物理偏移，无需手动维护 resume_offset=）
  #
  # 当前环境：boot.initrd.systemd.enable=true，initrd 中已含
  # systemd-hibernate-resume-generator（systemd 260），内核命令行只需
  # resume= 即可，systemd 自动用 FIEMAP 在休眠/恢复两条路径上定位偏移。
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 36 * 1024;
    }
  ];

  # swapfile 所在分区（=根分区）。用 by-label 更可读、重装不易变。
  # systemd-hibernate-resume 通过 FIEMAP 自动探测 swapfile 偏移，
  # 不再需要 resume_offset= 内核参数。
  boot.resumeDevice = "/dev/disk/by-label/NIXROOT";

  # amdgpu.ip_block_mask=0xfffff7ff：禁用 VPE IP 块，修复 AMD Phoenix 平台
  # （7840HS/Radeon 780M）休眠在 kernel >= 6.6.92 上卡死/写盘失败的问题。
  # 见 nixpkgs#413932、drm/amd#4178、Framework 社区相关讨论。
  boot.kernelParams = [
    "amdgpu.ip_block_mask=0xfffff7ff"
  ];

  # --- 用 fallocate 代替 dd 创建 swapfile，确保块连续 ---
  # NixOS 默认用 dd 写全零再 mkswap，在磁盘接近满时会产生严重碎片
  # （当前 ~15K extent）。此 service 抢先于 NixOS 内置 mkswap 执行，
  # 用 fallocate 一次分配连续空间。内置服务随后发现文件已存在且大小
  # 正确，直接跳过 dd 阶段，只负责后续 swapon。
  systemd.services.ensure-contiguous-swapfile = {
    description = "Pre-create swapfile with fallocate for contiguous extents";
    wantedBy = [ "var-lib-swapfile.swap" ];
    before = [ "mkswap-var-lib-swapfile.service" ];
    after = [ "local-fs.target" ];
    path = with pkgs; [ util-linux ];
    serviceConfig.Type = "oneshot";
    script = ''
      set -euo pipefail
      f=/var/lib/swapfile
      want_mb=36864
      if [ -f "$f" ]; then
        cur_mb=$(( $(stat -c "%s" "$f" 2>/dev/null || echo 0) / 1024 / 1024 ))
        if [ "$cur_mb" -eq "$want_mb" ]; then
          echo "swapfile already exists with correct size ($want_mb MB), nothing to do"
          exit 0
        fi
        echo "swapfile size mismatch (want $want_mb MB, got $cur_mb MB), recreating..."
        swapoff "$f" 2>/dev/null || true
        rm -f "$f"
      fi
      mkdir -p "$(dirname "$f")"
      echo "Creating $want_mb MB swapfile with fallocate..."
      fallocate -l ''${want_mb}M "$f"
      chmod 0600 "$f"
      mkswap "$f"
      echo "swapfile created, extents:"
      filefrag -v "$f" | head -5 || true
    '';
  };

  # 每次启动时检查 swapfile extent 数量是否过高。
  # resume_offset 已由 systemd-hibernate-resume（FIEMAP）自动探测，
  # 不再需要偏移比对。
  systemd.services.swapfile-frag-check = {
    description = "Check swapfile fragmentation";
    wantedBy = [ "multi-user.target" ];
    after = [ "var-lib-swapfile.swap" ];
    path = with pkgs; [ e2fsprogs util-linux ];
    serviceConfig.Type = "oneshot";
    script = ''
      set -euo pipefail
      swapfile="/var/lib/swapfile"
      if [ ! -f "$swapfile" ]; then
        echo "swapfile not found: $swapfile" >&2
        exit 0
      fi
      extent_count=$(filefrag -v "$swapfile" 2>/dev/null | grep -cE '^[[:space:]]*[0-9]+:' || echo 0)
      if [ "$extent_count" -gt 1000 ]; then
        echo "" >&2
        echo "============================================" >&2
        echo "  WARNING: swapfile has $extent_count extents — severely fragmented!" >&2
        echo "  Hibernation may fail or be extremely slow." >&2
        echo "  Action: sudo swapoff /var/lib/swapfile" >&2
        echo "          sudo rm /var/lib/swapfile" >&2
        echo "          sudo systemctl start ensure-contiguous-swapfile" >&2
        echo "          sudo swapon /var/lib/swapfile" >&2
        echo "============================================" >&2
        echo "" >&2
      elif [ "$extent_count" -gt 100 ]; then
        echo "NOTE: swapfile has $extent_count extents (moderate fragmentation)"
      else
        echo "swapfile OK: $extent_count extents"
      fi
    '';
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.Meta.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
}
