# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # systemd initrd 比传统 bash initrd 更现代、更快：
  # - 自动组装 MD/LVM/LUKS（systemd 原生驱动）
  # - systemd-hibernate-resume-generator 可自动探测 swapfile 偏移
  #   省掉 resume_offset 的手动维护（当前仍需显式写偏移做兜底）
  # - 如果用 Plymouth，图形化 LUKS 密码输入需要 systemd initrd
  boot.initrd.systemd.enable = true;

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXROOT";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/NIXBOOT";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # --- Zram 交换（内存压缩 swap）---
  # 日常桌面使用时优先走 zram（内存内压缩，比磁盘 swap 快）；
  # hibernate 时内核只写入真实 swapfile，不碰 zram。
  # 注意：zram 不能存休眠镜像，下方 /var/lib/swapfile 必须保留。
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
  };

  # --- Hibernate 配置（挂起到磁盘）---
  # 三样缺一不可：
  #   1) swap >= RAM（本机 RAM 27G，扩到 36G 留压缩镜像 + 余量）
  #   2) boot.resumeDevice —— 设了它，NixOS 自动生成 resume= 内核参数
  #   3) boot.kernelParams 里的 resume_offset= —— swapfile 在磁盘上的物理偏移（页面）
  # 已启用 boot.initrd.systemd，systemd-hibernate-resume-generator 理论可
  # 用 FIEMAP 自动探测偏移，但当前 nixpkgs 没打该 generator 进 initrd，
  # 所以显式 resume_offset 仍然必要（做兜底）。
  #
  # ⚠️  swapfile 一旦重建（扩容/移动/碎片重排），物理偏移会变，
  # 必须重新计算并更新下面的 resume_offset：
  #   sudo filefrag -v /var/lib/swapfile | python3 -c '
  #   import sys,re
  #   for l in sys.stdin:
  #     m=re.match(r"\s*\d+:\s+\d+\.\.\s*\d+:\s+(\d+)\.\.\s*\d+:\s+\d+",l)
  #     if m: print(int(m.group(1))); break'
  #   输出直接就是 resume_offset（单位是 4K 页面，不需要 ×8）。
  #   运行 schedule-resume-offset-check.service 可在下次 hibernate 前自动校验。
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 36 * 1024;
    }
  ];

  # swapfile 所在分区（=根分区）。用 by-label 更可读、重装不易变。
  boot.resumeDevice = "/dev/disk/by-label/NIXROOT";
  # resume_offset 单位是页面（PAGE_SIZE=4096B），刚好等于 ext4 的 4K 块号。
  # swapfile 第一 extent 在 4K 块 18720768，所以 resume_offset=18720768。
  # 注意：绝不要 ×8 转 512B 扇区！内核期望的是页面数。
  #
  # 如果 ensure-contiguous-swapfile 重建了 swapfile（大小变更/初次创建），
  # resume-offset-check 会在启动时检测偏移漂移并打印新值。
  # 到时把输出的 actual 值填到下面 resume_offset= 即可。
  #
  # amdgpu.ip_block_mask=0xfffff7ff：禁用 VPE IP 块，修复 AMD Phoenix 平台
  # （7840HS/Radeon 780M）休眠在 kernel >= 6.6.92 上卡死/写盘失败的问题。
  # 见 nixpkgs#413932、drm/amd#4178、Framework 社区相关讨论。
  boot.kernelParams = [
    "resume_offset=39057408"
    "amdgpu.ip_block_mask=0xfffff7ff"
  ];

  # --- 用 fallocate 代替 dd 创建 swapfile，确保块连续 ---
  # NixOS 默认用 dd 写全零再 mkswap，在磁盘接近满时会产生严重碎片
  # （当前 ~15K extent）。此 service 抢先于 NixOS 内置 mkswap 执行，
  # 用 fallocate 一次分配连续空间。内置服务随后发现文件已存在且大小
  # 正确，直接跳过 dd 阶段，只负责后续 swapon。
  systemd.services.ensure-contiguous-swapfile = {
    description = "Pre-create swapfile with fallocate for contiguous extents";
    wantedBy = [ "var-lib-swapfile.swap" ];
    before = [ "mkswap-var-lib-swapfile.service" ];
    after = [ "local-fs.target" ];
    path = with pkgs; [ util-linux ];
    serviceConfig.Type = "oneshot";
    script = ''
      set -euo pipefail
      f=/var/lib/swapfile
      want_mb=36864
      if [ -f "$f" ]; then
        cur_mb=$(( $(stat -c "%s" "$f" 2>/dev/null || echo 0) / 1024 / 1024 ))
        if [ "$cur_mb" -eq "$want_mb" ]; then
          echo "swapfile already exists with correct size ($want_mb MB), nothing to do"
          exit 0
        fi
        echo "swapfile size mismatch (want $want_mb MB, got $cur_mb MB), recreating..."
        swapoff "$f" 2>/dev/null || true
        rm -f "$f"
      fi
      mkdir -p "$(dirname "$f")"
      echo "Creating $want_mb MB swapfile with fallocate..."
      fallocate -l ''${want_mb}M "$f"
      chmod 0600 "$f"
      mkswap "$f"
      echo "swapfile created, extents:"
      filefrag -v "$f" | head -5 || true
    '';
  };

  # 每次启动时校验 swapfile 的健康状态：
  # 1) resume_offset 是否与内核 cmdline 一致
  # 2) extent 数量是否过高（碎片严重会导致休眠写盘失败）
  systemd.services.resume-offset-check = {
    description = "Verify swapfile resume_offset and fragmentation";
    wantedBy = [ "multi-user.target" ];
    after = [ "local-fs.target" ];
    path = with pkgs; [ e2fsprogs python3 util-linux ];
    serviceConfig.Type = "oneshot";
    script = ''
      set -euo pipefail
      swapfile="/var/lib/swapfile"
      if [ ! -f "$swapfile" ]; then
        echo "swapfile not found: $swapfile" >&2
        exit 0
      fi
      configured=$(cat /sys/power/resume_offset 2>/dev/null || echo 0)
      actual=$(filefrag -v "$swapfile" 2>/dev/null | \
        ${pkgs.python3}/bin/python3 -c "
import sys, re
for l in sys.stdin:
    m = re.match(r'\s*\d+:\s+\d+\.\.\s*\d+:\s+(\d+)\.\.\s*\d+:\s+\d+', l)
    if m:
        print(int(m.group(1)))
        break
")
      if [ "$configured" -eq 0 ]; then
        echo "WARNING: /sys/power/resume_offset is 0, hibernate will fail" >&2
        exit 0
      fi
      if [ "$configured" != "$actual" ]; then
        echo "" >&2
        echo "============================================" >&2
        echo "  CRITICAL: resume_offset mismatch!" >&2
        echo "  configured (kernel cmdline): $configured" >&2
        echo "  actual    (from filefrag):   $actual" >&2
        echo "" >&2
        echo "  Action: update resume_offset in hardware/zen14.nix:" >&2
        echo "    boot.kernelParams = [ ... resume_offset=$actual ... ]" >&2
        echo "  Then: sudo nixos-rebuild switch && sudo reboot" >&2
        echo "============================================" >&2
        echo "" >&2
      fi
      extent_count=$(filefrag -v "$swapfile" 2>/dev/null | grep -c '^\s*[0-9]' || echo 0)
      if [ "$extent_count" -gt 1000 ]; then
        echo "" >&2
        echo "============================================" >&2
        echo "  WARNING: swapfile has $extent_count extents — severely fragmented!" >&2
        echo "  Hibernation may fail or be extremely slow." >&2
        echo "  Action: sudo systemctl stop ensure-contiguous-swapfile" >&2
        echo "          sudo swapoff /var/lib/swapfile" >&2
        echo "          sudo rm /var/lib/swapfile" >&2
        echo "          sudo systemctl start ensure-contiguous-swapfile" >&2
        echo "          sudo swapon /var/lib/swapfile" >&2
        echo "          Update resume_offset and rebuild if the offset changed." >&2
        echo "============================================" >&2
        echo "" >&2
      elif [ "$extent_count" -gt 100 ]; then
        echo "NOTE: swapfile has $extent_count extents (moderate fragmentation)"
      fi
      echo "resume_offset OK: $actual (extents: $extent_count)"
    '';
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.Meta.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
}
